/**
 * @file Writes the generated docs from what tools/lib/docs.ts reads (PLAN.md §6.8, WP 0.6): `docs/INDEX.md` (a row per
 * registry kind declared with `defineKind`, PLAN.md §6.6, then module → purpose → exports → tests), `docs/API.md`
 * (each export with the first sentence of its doc comment, the public API first) and `docs/ERRORS.md` (every code
 * registered with `defineCodes`, with its message and fix).
 *
 * Invariants: the output depends only on the code, never on the clock or the machine, and is Prettier-formatted
 * with the repository's settings, so `prettier --check` passes on it and a stale file shows as a difference. Links
 * are relative to `docs/`. Modules are grouped by directory, in path order; the root's files come first.
 *
 * @example
 * import { readModules } from './docs';
 * const docs = await generateDocs(process.cwd(), readModules(process.cwd()));
 * Object.keys(docs); // ['docs/INDEX.md', 'docs/API.md', 'docs/ERRORS.md']
 * @see tools/cmd/docs.test.ts
 */
import { join } from 'node:path';
import { format, resolveConfig } from 'prettier';
import { firstSentence } from '../x';
import type { CodeDoc } from './docsCodes';
import { directoryOf, resolveExports, type DocComment, type ModuleDoc, type ResolvedExport } from './docs';

/** The generated files, by repository path. */
export const GENERATED = ['docs/INDEX.md', 'docs/API.md', 'docs/ERRORS.md'] as const;

/** The public barrels (PLAN.md §6.1): game code imports only these. */
export const BARRELS = ['engine/index.ts', 'engine/sim-api.ts'];

const BANNER =
  '<!-- Generated by `node x docs --write` from the file and export comments: edit those, not this file. -->';

/** A link from `docs/` to a repository file. */
const link = (path: string, text = path) => `[${text}](../${path})`;
/** Inline code that survives backticks inside it. */
const code = (text: string) => {
  const fence = '`'.repeat(Math.max(0, ...[...text.matchAll(/`+/g)].map((m) => m[0].length)) + 1);
  return fence.length > 1 ? `${fence} ${text} ${fence}` : `\`${text}\``;
};
/** The first sentence of a doc comment, or '' without one. */
const sentence = (doc?: DocComment) => (doc ? firstSentence(doc.description) : '');

/** Modules grouped by directory, root first, each group in path order. */
function byDirectory(modules: readonly ModuleDoc[]): [string, ModuleDoc[]][] {
  const groups = new Map<string, ModuleDoc[]>();
  for (const module of modules) {
    const dir = directoryOf(module.path);
    groups.set(dir, [...(groups.get(dir) ?? []), module]);
  }
  return [...groups].sort(([a], [b]) => (a === '' ? -1 : b === '' ? 1 : a.localeCompare(b, 'en')));
}

/** A table cell's text: one line, its pipes escaped. */
const cell = (text: string) => text.replace(/\s+/g, ' ').replace(/\|/g, '\\|');

/** The kinds section of `docs/INDEX.md`: one row per kind declared with `defineKind`, sorted by kind. */
export function kindRows(modules: readonly ModuleDoc[]): string[] {
  const kinds = modules
    .flatMap((module) => module.kinds)
    .filter((entry) => entry.description !== undefined)
    .sort((a, b) => a.kind.localeCompare(b.kind, 'en') || a.module.localeCompare(b.module, 'en'));
  const out = [
    '',
    '## Kinds',
    '',
    'Every registry kind (PLAN.md §6.6), from its `defineKind` call: `node x describe <kind>` lists its fields and ids.',
  ];
  if (kinds.length === 0) return [...out, '', 'No module declares a kind yet.'];
  out.push('', '| Kind | What it is | Declared in |', '| --- | --- | --- |');
  for (const entry of kinds) {
    out.push(`| ${code(entry.kind)} | ${cell(entry.description ?? '')} | ${link(entry.module, code(entry.module))} |`);
  }
  return out;
}

/** `docs/INDEX.md`, before formatting. */
export function indexMarkdown(modules: readonly ModuleDoc[]): string {
  const out = [
    BANNER,
    '',
    '# Index of modules',
    '',
    "Every registry kind, then every module of the engine and its tools: what it is for (its file comment's first",
    'sentence), what it exports and the tests that cover it. Each export, with the first sentence of its doc comment, is',
    'in [API.md](API.md); error and advice codes are in [ERRORS.md](ERRORS.md).',
    ...kindRows(modules),
  ];
  for (const [dir, group] of byDirectory(modules)) {
    out.push('', `## ${dir || 'The root'}`, '');
    for (const module of group) {
      out.push(
        `- ${link(module.path, code(module.path.slice(dir ? dir.length + 1 : 0)))}: ${module.purpose || '(no file comment)'}`,
      );
      const names = module.exports.map((item) => code(item.name));
      if (names.length) out.push(`  - Exports: ${names.join(', ')}`);
      if (module.tests.length) out.push(`  - Tests: ${module.tests.map((file) => link(file, code(file))).join(', ')}`);
    }
  }
  return `${out.join('\n')}\n`;
}

/** One API line: the export, its kind, where it is declared when elsewhere, and its first sentence. */
function apiLine(item: ResolvedExport, module: ModuleDoc): string {
  const inRepository = /\.(ts|js|mjs)$/.test(item.declaredIn) && !item.declaredIn.startsWith('.');
  const from = inRepository ? link(item.declaredIn, code(item.declaredIn)) : code(item.declaredIn);
  const where = item.declaredIn !== module.path ? ` from ${from}` : '';
  const text = item.name === 'default' && !item.doc ? module.purpose : sentence(item.doc);
  return `- ${code(item.name)} (${item.kind}${where}): ${text || '(undocumented)'}`;
}

/** `docs/API.md`, before formatting. */
export function apiMarkdown(root: string, modules: readonly ModuleDoc[]): string {
  const out = [
    BANNER,
    '',
    '# API',
    '',
    'Each export with the first sentence of its doc comment; the comment itself, at the link, is the full manual.',
    '',
    '## The public API',
    '',
    'Game code imports only `engine/index.ts` (pages) and `engine/sim-api.ts` (sim-side code), so this part is the',
    "game agent's manual.",
  ];
  const barrels = modules.filter((module) => BARRELS.includes(module.path));
  if (barrels.length === 0) out.push('', 'Neither barrel exists yet.');
  for (const module of barrels) {
    out.push('', `### ${link(module.path, code(module.path))}`, '');
    out.push(...resolveExports(root, module.path).map((item) => apiLine(item, module)));
  }
  out.push('', '## Engine internals and tools', '', 'For the agents who maintain the engine.');
  for (const module of modules) {
    if (BARRELS.includes(module.path) || module.exports.length === 0) continue;
    out.push('', `### ${link(module.path, code(module.path))}`, '');
    out.push(...resolveExports(root, module.path).map((item) => apiLine(item, module)));
  }
  return `${out.join('\n')}\n`;
}

/** `docs/ERRORS.md`, before formatting. */
export function errorsMarkdown(modules: readonly ModuleDoc[]): string {
  const codes = modules.flatMap((module) => module.codes).filter((entry) => entry.code !== '?');
  const out = [
    BANNER,
    '',
    '# Errors and advice codes',
    '',
    'Every code the engine prints, as `[CODE] message`, with its fix. Each module registers its own codes with',
    '`defineCodes` beside the code that raises them; tools/lib/docs.ts says how they are read.',
  ];
  if (codes.length === 0) out.push('', 'No module registers a code yet.');
  const areas = [...new Set(codes.map((entry) => entry.area))].sort();
  for (const area of areas) {
    out.push('', `## ${area}`);
    const inArea = codes.filter((entry) => entry.area === area).sort((a, b) => a.code.localeCompare(b.code, 'en'));
    for (const entry of inArea as CodeDoc[]) {
      out.push('', `### ${entry.code}`, '');
      out.push(`- Message: ${code(entry.template ?? '')}`);
      out.push(`- Fix: ${entry.fix ?? '(none)'}`);
      out.push(`- Registered in: ${link(entry.module, `${code(entry.module)} line ${entry.line}`)}`);
      if (entry.doc) out.push('', entry.doc);
    }
  }
  return `${out.join('\n')}\n`;
}

/** Formats Markdown as Prettier would format `file` under `root`. */
export async function formatMarkdown(root: string, file: string, text: string): Promise<string> {
  const path = join(root, file);
  const options = (await resolveConfig(path)) ?? {};
  return format(text, { ...options, filepath: path });
}

/** The generated docs' contents, formatted, by repository path. */
export async function generateDocs(root: string, modules: readonly ModuleDoc[]): Promise<Record<string, string>> {
  const raw: Record<string, string> = {
    'docs/INDEX.md': indexMarkdown(modules),
    'docs/API.md': apiMarkdown(root, modules),
    'docs/ERRORS.md': errorsMarkdown(modules),
  };
  const entries = await Promise.all(
    Object.entries(raw).map(async ([file, text]) => [file, await formatMarkdown(root, file, text)] as const),
  );
  return Object.fromEntries(entries);
}
